### ISSUE TITLE
fullnextsearch:index error

### ISSUE THREAD

**Issue by olli0815** [nextcloud/fullnextsearch_elasticsearch#1]
share/nextcloud# sudo -u www-data php occ fullnextsearch:index
index
PHP Fatal error:  Cannot use object of type Elasticsearch\Common\Exceptions\NoNodesAvailableException as array in /usr/share/nextcloud/apps/fullnextsearch_elasticsearch/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Transport.php on line 118

**Comment by daita** [comment]
please try 0.3.1
